### PR TITLE
v0.1.0: foundation + core UI + tagging

### LINKED ISSUE #1: Configurable revision limit per post type
## Goal

Let admins set how many revisions to keep for each public post type, overriding the global `WP_POST_REVISIONS`.

## Approach sketch

- Settings page under **Settings → Revisions** using the Settings API.
- One row per registered public post type, plus a global fallback.
- Hook into `wp_revisions_to_keep` (filter, per-post) to apply the chosen limit.
- Support "keep all" (true) and "disable" (0).

## Considerations

- Respect `WP_POST_REVISIONS` when defined in `wp-config.php` (document precedence).
- Only show post types that actually support revisions (`post_type_supports( $type, 'revisions' )`).
- No migration of existing revisions — the limit applies on next save.

## References

- Filter: `wp_revisions_to_keep`
- Constant: `WP_POST_REVISIONS`

### LINKED ISSUE #2: Admin overview listing revisions across the site
## Goal

Give admins a single site-wide screen that lists **posts with stored revisions**, sorted by how much bloat each post is carrying, with inline actions to clean up. This is the "where is my revision bloat?" dashboard — the entry point for cleanup work.

Not a list of individual revision rows — that would be millions of lines on large sites. The unit is the **parent post**, with an aggregated revision count per row.

---

## Where it lives

**Tools → Revisions** (submenu item). Tools is the right home: this screen is action-oriented (find and delete), not configuration. Settings under **Settings → Revisions** is a separate screen for the per-post-type limits (see #1).

Capability: `edit_others_posts` to view, stricter cap for bulk destructive actions (see #3).

---

## ASCII mockup — main overview

```
┌──────────────────────────────────────────────────────────────────────────────┐
│ Revisions Overview                                    Screen Options ▾  Help ▾│
├──────────────────────────────────────────────────────────────────────────────┤
│ Posts with stored revisions, heaviest first.                                  │
│ Select rows to bulk-delete revisions. The parent post is never touched.       │
│                                                                               │
│ [ All (247) | Pages (38) | Posts (184) | Products (25) ]                      │
│                                                                               │
│ ┌────────────────────────────────────────────────────────────────┐            │
│ │ Bulk actions    ▾   Apply    Any author ▾   Min revisions [10] │ Search [  ]│
│ └────────────────────────────────────────────────────────────────┘            │
│                                                                               │
│                                        247 items    « ‹ 1 of 13 › »           │
│                                                                               │
│ ┌───┬──────────────────────────────┬──────┬────────┬───────┬──────────┐       │
│ │ ☐ │ Title                         │ Type │ Author │ Revs↓ │ Oldest   │       │
│ ├───┼──────────────────────────────┼──────┼────────┼───────┼──────────┤       │
│ │ ☐ │ About Us                      │ Page │ admin  │   142 │ 3 y 2 mo │       │
│ │   │ Edit · Compare · Delete revs  │      │        │       │          │       │
│ ├───┼──────────────────────────────┼──────┼────────┼───────┼──────────┤       │
│ │ ☐ │ 2025 Annual Report            │ Post │ janed  │    89 │ 14 mo    │       │
│ ├───┼──────────────────────────────┼──────┼────────┼───────┼──────────┤       │
│ │ ☐ │ Product launch: Widget Pro    │ Post │ markw  │    67 │ 8 mo     │       │
│ ├───┼──────────────────────────────┼──────┼────────┼───────┼──────────┤       │
│ │ ☐ │ Privacy Policy                │ Page │ admin  │    54 │ 2 y      │       │
│ ├───┼──────────────────────────────┼──────┼────────┼───────┼──────────┤       │
│ │ ☐ │ Team                          │ Page │ admin  │    48 │ 1 y      │       │
│ └───┴──────────────────────────────┴──────┴────────┴───────┴──────────┘       │
│                                                                               │
│ Bulk actions    ▾   Apply                                                     │
│                                                                               │
│                                        247 items    « ‹ 1 of 13 › »           │
└──────────────────────────────────────────────────────────────────────────────┘
```

Conventions: standard `WP_List_Table` layout — tabs like the core *All | Published | Draft* switcher, bulk dropdown + apply above and below, pagination top-right and bottom-right, sortable column headers with arrow indicators.

---

## Columns

Native WP sortable-column behavior. ✓ = visible by default.

| Col            | Default | Sortable | Notes                                                               |
|----------------|:-------:|:--------:|---------------------------------------------------------------------|
| Checkbox       |    ✓    |    —     | Bulk selection                                                      |
| Title          |    ✓    |    ✓     | Links to edit screen; row actions underneath                        |
| Type           |    ✓    |    ✓     | Post-type label ("Page", "Post", custom)                            |
| Author         |    ✓    |    ✓     | Parent post author                                                  |
| Revisions      |    ✓    |    ✓     | Count of revision rows (excludes autosaves by default — see #8)     |
| Oldest         |    ✓    |    ✓     | Age of the oldest stored revision, human diff ("3 y 2 mo")          |
| Last modified  |         |    ✓     | Parent post modified date (off by default, via Screen Options)      |
| Est. size      |         |    —     | Rough byte size sum of revision post_content (off by default)       |
| Autosaves      |         |    ✓     | Separate autosave count (off by default; see #8)                    |

Default sort: **Revisions desc** — heaviest first is what admins want.

---

## Row actions (hover state)

```
│ About Us                         │
│ Edit · Compare · Delete revisions · Keep latest ▾  │
                                            │
                                            ├─ Keep latest 5
                                            ├─ Keep latest 10
                                            ├─ Keep latest 25
                                            └─ Keep latest N…
```

- **Edit** → standard post edit screen
- **Compare** → native `revision.php` for this post
- **Delete revisions** → deletes all revisions for this one post (with confirmation)
- **Keep latest N** → submenu; deletes everything except the N newest revisions

All row actions are nonced and gated by `edit_post` on the parent.

---

## Filters

Top filter bar (inside the tablenav):

- **Post type** tab strip (All / Pages / Posts / custom types with `supports('revisions')`)
- **Author** dropdown (reuses core `wp_dropdown_users`)
- **Min revisions** numeric input (show only posts with ≥ N revisions; default 10 to cut noise)
- **Search** — searches post titles (reuses `posts_search` behavior against parent posts)

Filters are URL-driven (`?post_type=page&min=20`) so admins can bookmark/share.

---

## Bulk actions (dropdown above and below the table)

```
Bulk actions ▾
 ├─ Delete all revisions
 ├─ Keep latest 5
 ├─ Keep latest 10
 └─ Delete autosaves only
```

Full implementation lives in #3. This issue just defines the UI surface.

---

## Confirmation step for destructive bulk actions

Modal rendered with WP core's `wp-admin/includes/class-wp-upgrader-skin.php`-style block — actually simpler: a standard interstitial page between "Apply" and the actual delete, matching how core handles bulk post deletion.

```
┌──────────────────────────────────────────────────────────────┐
│ Delete revisions                                              │
├──────────────────────────────────────────────────────────────┤
│ You selected 12 posts. This will delete 847 revisions         │
│ and free approximately 38 MB of database space.               │
│                                                               │
│ Parent posts and their published content will not be          │
│ affected. Autosaves will also be preserved.                   │
│                                                               │
│   ☐ Also delete autosaves                                     │
│                                                               │
│                       [ Cancel ]   [ Delete 847 revisions ]   │
└──────────────────────────────────────────────────────────────┘
```

The number shown (847) comes from a **dry-run query** executed before the confirmation page renders — never a guess. See #3.

---

## Result feedback

After the destructive action runs, return to the overview with a `wp_admin_notice()`:

```
┌──────────────────────────────────────────────────────────────┐
│ ✓ Deleted 847 revisions from 12 posts. Freed ~38 MB.          │
└──────────────────────────────────────────────────────────────┘
```

Red notice for partial failures, with a link to a details view.

---

## Empty / filtered-out state

```
┌──────────────────────────────────────────────────────────────┐
│ No posts match these filters.                                 │
│                                                               │
│                   [ Clear filters ]                           │
└──────────────────────────────────────────────────────────────┘
```

First-run empty state (no revisions anywhere on the site) gets a different message: "Nothing to clean up — your site has no stored revisions."

---

## Screen Options

Native WP Screen Options panel for column visibility + per-page:

```
┌───────────────────────────────────────────────┐
│ Columns                                        │
│  ☑ Title       ☑ Type        ☑ Author          │
│  ☑ Revisions   ☑ Oldest      ☐ Last modified   │
│  ☐ Est. size   ☐ Autosaves                     │
│                                                │
│ Pagination                                     │
│  Number of items per page:  [ 20 ]             │
│                                                │
│                                  [ Apply ]     │
└───────────────────────────────────────────────┘
```

---

## Technical notes

**One aggregation query per page load**, not N+1. Something along these lines:

```sql
SELECT
  p.ID, p.post_title, p.post_type, p.post_author, p.post_modified,
  COUNT(r.ID)                     AS rev_count,
  MIN(r.post_date)                AS oldest_rev,
  SUM(LENGTH(r.post_content))     AS est_size_bytes
FROM wp_posts p
INNER JOIN wp_posts r
  ON r.post_parent = p.ID
  AND r.post_type = 'revision'
  AND r.post_name NOT LIKE CONCAT(p.ID, '-autosave-%')
WHERE p.post_status IN ('publish','draft','pending','private','future')
GROUP BY p.ID
HAVING rev_count >= %d
ORDER BY rev_count DESC
LIMIT %d OFFSET %d;
```

- The `HAVING rev_count >= N` clause uses the **Min revisions** filter to reduce the result set before pagination.
- A parallel `COUNT(*)` query (same WHERE/HAVING, no LIMIT) fills the paginator.
- Cache both query results in a transient keyed by the filter state (~60s TTL) — this page doesn't need to be real-time.
- Use `$wpdb->prefix` and `$wpdb->prepare()` religiously.

**Post-type filtering** happens via `p.post_type IN (…)` — compose from the selected tab.

**Autosave exclusion** uses `post_name` suffix match. The `-autosave-` pattern is how core names autosave rows. Toggle via the autosave column / filter (see #8).

---

## Edge cases

- **Posts with zero revisions** don't appear. This screen is about cleanup, not a complete post listing.
- **Trashed parent posts** — include them, so admins can clean up revisions for posts being reviewed for deletion. Mark them visually (greyed row, "(Trashed)" suffix on title).
- **Orphaned revisions** (parent hard-deleted) don't appear here — they need #6's dedicated sweep.
- **Private / password-protected posts** — respect `read_private_posts` capability; filter SQL accordingly.
- **Multisite** — per-site screen only. Network-wide view is a separate issue.
- **Very large result sets** — the `HAVING` + `LIMIT` keeps this fast, but add an SQL `EXPLAIN` check during development on a seeded 1M-revision fixture.
- **Column sort on `oldest`** — MySQL `MIN(r.post_date)` is indexed poorly; may need a computed column or a separate index. Revisit if EXPLAIN shows a filesort on large sites.

---

## Out of scope for this issue

- The actual deletion logic → #3 (Bulk-delete revisions)
- Post-type-level limit configuration → #1
- Post list table revision column → #4
- Scheduled cleanup → #5
- Orphaned-revision sweep → #6
- Autosave visibility toggle → #8

---

## References

- Class: [`WP_List_Table`](https://developer.wordpress.org/reference/classes/wp_list_table/) — extend in `src/Admin/Overview/RevisionsListTable.php`
- Filter: [`post_row_actions`](https://developer.wordpress.org/reference/hooks/post_row_actions/)
- Function: [`add_management_page`](https://developer.wordpress.org/reference/functions/add_management_page/) — to register under Tools
- Function: [`wp_admin_notice`](https://developer.wordpress.org/reference/functions/wp_admin_notice/) — for result feedback (WP 6.4+)
- Core example to mirror: `wp-admin/users.php` + `WP_Users_List_Table`

### LINKED ISSUE #3: Bulk-delete revisions from the admin overview
## Goal

Select posts in the overview and delete their revisions in one action.

## Approach sketch

- Bulk actions on the overview's `WP_List_Table`:
  - Delete **all** revisions for the selected posts
  - Keep only the **latest N** revisions
- Dry-run preview before execution ("this will delete X revisions across Y posts").
- Batched deletion to avoid timeouts on large result sets.

## Considerations

- Capability gate: `edit_others_posts` (or a dedicated custom cap).
- Nonce on every destructive action.
- Never delete the parent post — guard queries with `post_type = 'revision'`.
- Use `wp_delete_post_revision()` so hooks fire correctly.
- Report result count in a native `wp_admin_notice()`.

## References

- Function: `wp_delete_post_revision()`
- Method: `WP_List_Table::bulk_actions()`

### LINKED ISSUE #4: Add revision count column to post list tables
## Goal

Show per-post revision count on the existing Posts/Pages list screens, plus a row action to manage revisions.

## Approach sketch

- Register a column via `manage_{post_type}_posts_columns` and render it via `manage_{post_type}_posts_custom_column`.
- Aggregate counts for the current page via one SQL query (`post_parent IN (…)`) cached per request.
- Add a row action "Manage revisions" linking to the native `revision.php`.

## Considerations

- Add the column only for post types that support revisions.
- Make the column sortable (`manage_edit-{post_type}_sortable_columns`).
- Cache carefully — counts can change during the request.

## References

- Filters: `manage_posts_columns`, `manage_posts_custom_column`, `post_row_actions`

### LINKED ISSUE #10: Dashboard widget with revision stats
## Goal

Surface revision bloat on the admin dashboard so editors/admins notice it without visiting a dedicated page.

## Approach sketch

- Register via `wp_add_dashboard_widget`.
- Stats to display:
  - Total revision rows site-wide
  - Estimated DB space used by revisions
  - Top 5 posts by revision count (with links)
  - Link to the overview page and cleanup action

## Considerations

- Cache aggregated stats (transient, ~1h) — dashboard loads often, these queries are expensive.
- Capability-gate the widget (don't show to subscribers).
- Keep HTML compact; dashboards are crowded.

## References

- Function: `wp_add_dashboard_widget`

### LINKED ISSUE #11: Per-post override for revision retention
## Goal

Let editors override the post-type revision limit on individual posts — useful for high-churn landing pages or legally-sensitive posts that need full history.

## Approach sketch

- Meta box on the edit screen (classic + block editor) storing a `_advanced_revisions_keep` post meta value.
- Integers and "unlimited" / "use default" options.
- Honor the override in the `wp_revisions_to_keep` filter before applying the per-type rule.

## Considerations

- Capability check: only editors / admins (configurable).
- Block editor support via `register_post_meta` + a `PluginDocumentSettingPanel` — or keep a classic meta box only to stay fully native.
- Document precedence: per-post > per-type > global fallback > `WP_POST_REVISIONS`.

## References

- Filter: `wp_revisions_to_keep`
- Functions: `add_meta_box`, `register_post_meta`

### LINKED ISSUE #13: Revision tagging, notes, and cleanup protection
## Goal

Let editors **tag**, **annotate**, and **protect** individual revisions. A tagged revision is discoverable ("show me all revisions tagged `legal-2025`"); an annotated revision has a human-readable note explaining why it matters ("pre-migration snapshot"); a **protected** revision is skipped by every cleanup path (bulk delete, scheduled cleanup, orphan sweep, WP-CLI).

This fills a real gap — only [Revision Notes](https://wordpress.org/plugins/revision-notes/) (Helen Hou-Sandí) ever shipped note-on-save, and it's been abandoned since Feb 2021. Nothing in the ecosystem does multi-tag + protection flag + filtering.

---

## Why this blocks #3, #5, #6, #7

Every cleanup path must respect the protection flag. Without this mechanism in place, those features have no way to spare the revisions that actually matter. This issue must land first (or in parallel with the shared protection-check service).

---

## Concepts

| Concept    | What it is                                           | Scope           | Storage                                |
|------------|------------------------------------------------------|-----------------|----------------------------------------|
| **Tag**    | Short controlled-vocabulary label (`legal-2025`)     | Site-wide reuse | Custom taxonomy `revision_tag`         |
| **Note**   | Free-text comment on one revision                    | One revision    | Post meta `_advanced_revisions_note`   |
| **Protected** | Boolean on a *tag*; any revision wearing a protected tag is spared by cleanup | Tag attribute | Term meta `protected` (bool)           |

**Key design decision:** protection is a **tag attribute**, not a per-revision flag. This keeps policy declarative — create a tag "Legal review", mark the tag as protected, apply it to any revision you need to preserve. Un-mark the tag later and all its revisions are eligible for cleanup again.

---

## Supported operations

All operations apply to **any** revision — newly saved or years old. Tagging is never a "set once" deal.

| Operation                                  | Where                                                      |
|--------------------------------------------|------------------------------------------------------------|
| **Tag a new save**                         | Sidebar panel in the post editor (applied to next revision)|
| **Tag an existing revision (retroactive)** | Metabox on the native `revision.php` compare screen        |
| **Remove a tag from a revision**           | Click × on the tag chip — in the sidebar *or* on `revision.php` |
| **Edit the note on a revision**            | Editable text on `revision.php`; blank = no note           |
| **Add a new tag to the vocabulary**        | Tools → Revisions → Tags (auto-generated `edit-tags.php`)  |
| **Rename a tag**                           | Term edit screen — label propagates everywhere it's used   |
| **Delete a tag from the vocabulary**       | Term edit screen — revisions stay, associations drop       |
| **Toggle `protected` on a tag**            | Checkbox on the term edit screen — effective immediately   |
| **Bulk tag / untag from the overview**     | *(Stretch)* Bulk action on #2's `WP_List_Table`            |

Removal is always capability-gated the same way as the corresponding add: removing a tag from a revision requires `edit_post` on the parent; removing a tag from the vocabulary requires `manage_options`.

No operation is irreversible in a destructive sense — dropping a tag association doesn't touch the revision's content; deleting a vocabulary term doesn't delete revisions.

---

## ASCII mockup — block editor sidebar panel

Added to the post editor sidebar (classic meta box for non-block editor):

```
┌────────────────────────────────────────────┐
│ Revisions                                   │
├────────────────────────────────────────────┤
│ This post has 47 revisions.                 │
│ 3 are protected.                            │
│                                             │
│ → View all revisions                        │
│ → Compare revisions                         │
│                                             │
│ ─── Note for next save ─────────────        │
│ ┌──────────────────────────────────────┐    │
│ │ e.g. "post-migration snapshot"        │    │
│ │                                       │    │
│ └──────────────────────────────────────┘    │
│                                             │
│ ─── Tags for next save ─────────────        │
│ ┌──────────────────────────────────────┐    │
│ │ [Legal review ×] [Approved ×]         │    │
│ │ Add tag…                              │    │
│ └──────────────────────────────────────┘    │
└────────────────────────────────────────────┘
```

The note/tags entered here are stashed on the **parent post** as pending meta (`_advanced_revisions_pending_note`, `_advanced_revisions_pending_tags`). When `_wp_put_post_revision` fires, the plugin copies pending meta onto the newly-created revision row and clears the parent's pending meta. This sidesteps the chicken-and-egg problem that the revision post doesn't exist yet when the editor is typing.

---

## ASCII mockup — revision details on `revision.php`

A metabox below the native compare view, on the existing revision screen:

```
┌───────────────────────────────────────────────────────────────────┐
│ Revision details                                                   │
├───────────────────────────────────────────────────────────────────┤
│ Saved:  2025-11-14 09:47 by markw                                  │
│ Note:   "Pre-redesign snapshot"                                    │
│                                                                    │
│ Tags:   [Legal review ×] [Pre-redesign ×]   Add tag…               │
│                                                                    │
│ 🔒 Protected from cleanup — inherited from tag "Legal review"      │
└───────────────────────────────────────────────────────────────────┘
```

This is the **retroactive** tagging path — tag a revision that already exists, not just the next one.

---

## ASCII mockup — revision tags management

Auto-generated from the `register_taxonomy` call. Lives under **Tools → Revisions → Tags**:

```
┌──────────────────────────────────────────────────────────────────────────┐
│ Revision Tags                                       Screen Options ▾  Help ▾│
├──────────────────────────────────────────────────────────────────────────┤
│ Add new tag                                                                │
│   Name         [                              ]                            │
│   Slug         [                              ]                            │
│   Description  [                              ]                            │
│   ☐ Protect revisions with this tag from cleanup                          │
│                                                    [ Add new tag ]        │
│ ─────────────────────────────────────────────────────────────────────     │
│ ┌──┬─────────────────────┬──────────────┬───────────┬──────────────┐     │
│ │☐ │ Name                 │ Slug         │ Protected │  Revisions    │     │
│ ├──┼─────────────────────┼──────────────┼───────────┼──────────────┤     │
│ │☐ │ Legal review 2025    │ legal-2025   │    🔒     │      12       │     │
│ │☐ │ Pre-redesign         │ pre-redesign │           │       3       │     │
│ │☐ │ Approved             │ approved     │    🔒     │      47       │     │
│ └──┴─────────────────────┴──────────────┴───────────┴──────────────┘     │
└──────────────────────────────────────────────────────────────────────────┘
```

---

## ASCII mockup — tag filter + column on the overview (#2)

```
┌─────────────────────────────────────────────────────────────────┐
│ Bulk actions ▾  Apply  All types ▾  Any tag ▾  Min revs [10]     │
│                            └─ Any tag                             │
│                               ├─ No tags                          │
│                               ├─ Has any tag                      │
│                               ├─ Has protected tag                │
│                               ├─ legal-2025                       │
│                               ├─ pre-redesign                     │
│                               └─ approved                         │
└─────────────────────────────────────────────────────────────────┘
```

And a new optional column on the #2 overview (off by default, togglable via Screen Options):

```
│ ☐ │ About Us       │ Page │ admin  │   142 │ 3 y 2 mo │ legal-2025 │
│   │                │      │        │       │          │ approved   │
│ ☐ │ 2025 Report    │ Post │ janed  │    89 │ 14 mo    │ approved   │
```

Row counts should read "142 total · 12 protected" when any revisions on the row are protected.

---

### 1. Taxonomy

```php
register_taxonomy( 'revision_tag', 'revision', [
    'public'            => false,
    'show_ui'           => true,
    'show_in_menu'      => false,   // we surface it under Tools → Revisions ourselves
    'show_admin_column' => false,   // we render our own column on the overview
    'show_in_rest'      => true,    // needed for block-editor sidebar
    'rewrite'           => false,
    'hierarchical'      => false,
    'labels'            => [ /* "Revision tag" / "Revision tags" */ ],
    'capabilities'      => [
        'manage_terms' => 'manage_options',
        'edit_terms'   => 'manage_options',
        'delete_terms' => 'manage_options',
        'assign_terms' => 'edit_others_posts',
    ],
] );
```

Tags target `post_type = 'revision'`. WordPress doesn't forbid this — the revision post type is just another post type from `register_taxonomy`'s perspective.

### 2. Term meta for protection

`protected` (bool) on each term. Read during cleanup:

```sql
-- "Get all revision IDs for parent %d that wear at least one protected tag"
SELECT DISTINCT tr.object_id
FROM wp_term_relationships tr
INNER JOIN wp_term_taxonomy tt     ON tt.term_taxonomy_id = tr.term_taxonomy_id
INNER JOIN wp_termmeta tm          ON tm.term_id = tt.term_id
INNER JOIN wp_posts r              ON r.ID = tr.object_id
WHERE tt.taxonomy = 'revision_tag'
  AND tm.meta_key = 'protected' AND tm.meta_value = '1'
  AND r.post_parent = %d
  AND r.post_type = 'revision';
```

### 3. Note meta

- `_advanced_revisions_note` (string) on the revision itself
- `_advanced_revisions_pending_note` (string) on the **parent** post — set by the sidebar, consumed + cleared by `_wp_put_post_revision`
- `_advanced_revisions_pending_tags` (array of term slugs) on the **parent** post — same flow

Register these via `register_post_meta` so they're REST-visible for the block editor.

### 4. Hook into revision save

```php
add_action( '_wp_put_post_revision', function ( $revision_id ) {
    $parent_id = wp_get_post_parent_id( $revision_id );
    if ( ! $parent_id ) return;

    $pending_note = get_post_meta( $parent_id, '_advanced_revisions_pending_note', true );
    if ( $pending_note !== '' ) {
        update_post_meta( $revision_id, '_advanced_revisions_note', $pending_note );
        delete_post_meta( $parent_id, '_advanced_revisions_pending_note' );
    }

    $pending_tags = get_post_meta( $parent_id, '_advanced_revisions_pending_tags', true );
    if ( is_array( $pending_tags ) && $pending_tags !== [] ) {
        wp_set_object_terms( $revision_id, $pending_tags, 'revision_tag', false );
        delete_post_meta( $parent_id, '_advanced_revisions_pending_tags' );
    }
}, 10, 1 );
```

### 5. Protection API (shared service)

Single public method used by every cleanup path:

```php
// src/Revisions/ProtectionService.php
public function filter_deletable( array $revision_ids ): array;
// Returns the subset of $revision_ids that are NOT protected.
```

#3, #5, #6, #7 all call this before issuing `wp_delete_post_revision()`. No duplicated SQL.

---

## Integration with cleanup features

| Issue | What changes                                                                                |
|-------|---------------------------------------------------------------------------------------------|
| #3    | Bulk delete confirmation page shows "847 eligible, 12 protected will be skipped"            |
| #5    | Scheduled cleanup runs `filter_deletable()` before deleting; logs skipped count              |
| #6    | Orphan sweep does the same                                                                   |
| #7    | WP-CLI `delete` / `cleanup` honor protection; add `--force-protected` flag to override       |

---

## Capabilities

- **Tag/note a revision**: `edit_post` on the parent
- **Manage the tag vocabulary**: `manage_options` (configurable)
- **Bypass protection**: custom cap `bypass_revision_protection`, off by default for everyone

---

## Edge cases

- **Deleting a tag** removes the association but not the revisions. Terms can be deleted cleanly.
- **Toggling `protected` on/off** takes effect immediately — no migration; cleanup reads term meta at query time.
- **Tag autocomplete** in the sidebar needs REST; `show_in_rest => true` covers it.
- **Multisite**: tag vocabulary is per-site (taxonomy data lives in each site's `wp_terms`).
- **Exporting revisions with tags** (WXR / `wp export`): tags are taxonomy data, so they export naturally. Note meta exports via post meta.
- **REST API shape**: `/wp/v2/revisions/<id>` should expose `revision_tag` and the note meta. This likely requires registering the taxonomy's REST base and opting meta into REST (`show_in_rest => true` on `register_post_meta`).
- **Revision deletion**: when a revision is deleted (for any reason), its term relationships and meta are cleaned up by core automatically via `wp_delete_post()`.
- **Parent post deletion**: revisions are deleted with the parent; their tags go with them. Term counts update naturally.
- **Performance**: the `revision_tag` taxonomy is small (user-managed vocabulary), so autocomplete and filter queries are cheap. The protection check in cleanup is a single JOIN against `wp_termmeta` + `wp_term_relationships`.

---

## Out of scope

- **Sharing tag vocabulary across a multisite network** — stretch goal, tracked separately if requested
- **Automatic tagging by rule** ("tag any revision where post_status changes to publish") — stretch, tracked separately
- **Public-facing display** of revision tags — this is an admin-only concept

---

## References

- [`register_taxonomy`](https://developer.wordpress.org/reference/functions/register_taxonomy/)
- [`register_post_meta`](https://developer.wordpress.org/reference/functions/register_post_meta/)
- [`_wp_put_post_revision`](https://developer.wordpress.org/reference/hooks/_wp_put_post_revision/) action
- [`wp_set_object_terms`](https://developer.wordpress.org/reference/functions/wp_set_object_terms/)
- Term meta: [`add_term_meta`](https://developer.wordpress.org/reference/functions/add_term_meta/), [`get_term_meta`](https://developer.wordpress.org/reference/functions/get_term_meta/)
- Prior art (abandoned): [Revision Notes](https://wordpress.org/plugins/revision-notes/) / [GitHub](https://github.com/helen/revision-notes)

### LINKED ISSUE #14: Dev fixtures plugin: sibling plugin with test custom post types
## Goal

Create a **separate sibling plugin** — `advanced-revisions-dev/` — that lives in this repo but **never ships with the production plugin**. It hosts the test CPTs and (via #15, #16) the seed WP-CLI commands. This keeps test-only code out of the published `advanced-revisions.zip` while keeping it version-controlled alongside the API it exercises.

Pattern taken from [inpsyde/WP-Stash](https://github.com/inpsyde/WP-Stash/tree/main/wp-stash-test-plugin).

---

## Repo layout after this issue

```
advanced-revisions/               # repo root
├── plugin.php                    # main plugin entry (ships)
├── src/                          # Apermo\AdvancedRevisions  (ships)
├── advanced-revisions-dev/       # sibling dev plugin (NEVER ships)
│   ├── advanced-revisions-dev.php    # entry + inline autoloader
│   └── src/
│       ├── TestPostTypes.php     # this issue
│       └── CLI/                  # populated by #15, #16
├── .gitattributes                # adds: advanced-revisions-dev/ export-ignore
└── …
```

---

## Sibling plugin: `advanced-revisions-dev.php`

Standard WordPress plugin header (not MU) — activation is **manual/opt-in**, following WP-Stash's example. Activating it in production would be a mistake but not an accident.

```php
<?php
/**
 * Plugin Name: Advanced Revisions – Dev Fixtures
 * Description: Test CPTs and seed WP-CLI commands for developing Advanced
 *              Revisions. DO NOT INSTALL IN PRODUCTION.
 * Version:     0.1.0
 * Requires PHP: 8.1
 * License:     GPL-2.0-or-later
 */

declare(strict_types=1);

namespace Apermo\AdvancedRevisionsDev;

\defined( 'ABSPATH' ) || exit();

// Inline PSR-4 autoloader — the dev plugin must not depend on the main
// plugin's composer autoload so it can be activated on a minimal install.
spl_autoload_register( static function ( string $class ): void {
    $prefix = __NAMESPACE__ . '\\';
    if ( ! str_starts_with( $class, $prefix ) ) {
        return;
    }
    $relative = substr( $class, strlen( $prefix ) );
    $path     = __DIR__ . '/src/' . str_replace( '\\', '/', $relative ) . '.php';
    if ( is_readable( $path ) ) {
        require $path;
    }
} );

add_action( 'init', [ TestPostTypes::class, 'register' ] );
```

**Namespace:** `Apermo\AdvancedRevisionsDev\` — distinct from the production `Apermo\AdvancedRevisions\`. Prevents accidental cross-wiring and makes grep-filtering obvious.

**Autoloader:** inline, not Composer. The dev plugin is self-contained.

---

## Test post types

Registered in `advanced-revisions-dev/src/TestPostTypes.php`:

| Slug              | Label        | `supports('revisions')` | Hierarchical | Public | Purpose                                 |
|-------------------|--------------|:-----------------------:|:------------:|:------:|------------------------------------------|
| `ar_test_article` | Article      |            ✓            |              |   ✓    | Flat public baseline                     |
| `ar_test_page`    | Test Page    |            ✓            |      ✓       |   ✓    | Hierarchical — exercises parent UX       |
| `ar_test_product` | Product      |            ✓            |              |   ✓    | Has registered meta (tests #9)           |
| `ar_test_note`    | Note         |            —            |              |   ✓    | Revisions OFF — negative coverage        |
| `ar_test_private` | Private doc  |            ✓            |              |        | Non-public — exercises capability gating |

Built-in `post` / `page` still exist; these CPTs extend the matrix, not replace it.

Each CPT uses its own capability type so capability tests aren't polluted by core-post caps. `ar_test_product` registers real post meta via `register_post_meta` (`show_in_rest => true`) so #9 has something to target.

---

## Exclusion from the production ZIP

`.gitattributes` addition:

```
advanced-revisions-dev/  export-ignore
/advanced-revisions-dev  export-ignore
```

This keeps the sibling directory out of `git archive` — which is what the WP.org SVN deploy workflow uses to build the distributed ZIP. Double-check the deploy workflow's file list as a belt-and-braces measure when #14 is implemented.

---

## DDEV activation

Two touchpoints:

1. **Mount** — `.ddev/config.yaml` (or the ddev-orchestrate config) symlinks `advanced-revisions-dev/` into `.ddev/wordpress/wp-content/plugins/advanced-revisions-dev/` alongside the main plugin's symlink.
2. **Activation** — `ddev orchestrate` runs `wp plugin activate advanced-revisions-dev` after the main plugin is activated. Add this to the orchestrate hook config.

Developer can always `wp plugin deactivate advanced-revisions-dev` to test a "real user" scenario on the same DDEV instance.

---

## Verification checklist

- [ ] `advanced-revisions-dev/` exists with the entry file + namespace autoloader
- [ ] 5 test CPTs register on `init`
- [ ] `.gitattributes` excludes the sibling dir
- [ ] `git archive HEAD | tar t` does NOT list `advanced-revisions-dev/` files
- [ ] `ddev orchestrate` auto-activates the dev plugin
- [ ] Main plugin's `composer.json` is **unchanged** — no cross-autoload wiring
- [ ] `wp plugin deactivate advanced-revisions-dev` cleanly hides the test CPTs from the admin

---

## Out of scope

- WP-CLI seed commands for content → #15
- WP-CLI seed commands for revisions / autosaves / orphans → #16
- Test plan + scenarios → #17

---

## References

- Reference pattern: [inpsyde/WP-Stash → wp-stash-test-plugin/](https://github.com/inpsyde/WP-Stash/tree/main/wp-stash-test-plugin)
- [`register_post_type`](https://developer.wordpress.org/reference/functions/register_post_type/)
- [`register_post_meta`](https://developer.wordpress.org/reference/functions/register_post_meta/)
- Git: [`export-ignore` gitattributes](https://git-scm.com/docs/gitattributes#_creating_an_archive)

### LINKED ISSUE #15: Test fixtures: WP-CLI command to seed dummy content
## Goal

WP-CLI command that seeds realistic **post content** across every enabled post type (core `post` / `page` + the test CPTs from #14). Deterministic when given a seed value; idempotent by default; cleanly reversible.

Content here means **posts only** — revisions and autosaves live in #16 so the two mechanisms can be composed independently ("seed content without revisions", "seed revisions onto existing content", etc.).

---

### `wp advanced-revisions fixtures:content [--flags…]`

Creates posts. Flags:

| Flag              | Default   | Meaning                                                    |
|-------------------|-----------|------------------------------------------------------------|
| `--count=N`       | `50`      | Posts per enabled post type                                |
| `--seed=N`        | (random)  | RNG seed for reproducibility                               |
| `--authors=N`     | `3`       | Rotate through N created test authors                      |
| `--date-spread=N` | `1095`    | Spread `post_date` across the last N days (~3 y)           |
| `--status-mix`    | `publish` | `publish`, `mixed` (publish/draft/pending/private), `all`  |
| `--post-types=…`  | (all)     | Comma-separated slugs to target a subset                   |
| `--force`         | off       | Delete previously seeded content before re-seeding         |

Output: one-line summary per post type (`Seeded 50 posts into ar_test_article`), final total.

### `wp advanced-revisions fixtures:reset-content`

Deletes everything this command seeded — nothing else. Uses `wp_delete_post( $id, true )` to force-delete (skip trash).

---

## Marker meta

Every seeded post gets `_ar_seeded => 1` meta. The reset command matches on this so it can never touch real content. The same marker lets #16 find "seed-created" posts to attach revisions to.

---

## Content generation

- Titles / bodies: procedurally generated (no external API). A small vocabulary + template sentences is enough — the goal is *plausible-looking*, not Pulitzer-winning. Examples: "How to configure X for Y", "Review: [Widget] v2".
- Excerpts: first 160 chars of body, occasionally blank to exercise "no excerpt" paths.
- Featured image: skipped (not relevant to revisions).
- `post_author`: rotated through authors created on first run (`ar_test_author_1` … `_N`, role `editor`).
- `post_date`: uniform random between now and `--date-spread` days ago.

---

## Determinism

`--seed=N` sets `mt_srand( $seed )` (or an injected Mersenne Twister wrapped class) so two runs with the same seed produce byte-identical content. Essential for E2E fixtures that CI relies on.

---

## Idempotency

Default behavior: running the command twice **adds more** content (no deduplication check — the seed value is what controls reproducibility). `--force` does a reset-content first.

---

## Scale targets

Must finish in a reasonable time for:

| Scenario  | Counts                                 | Target        |
|-----------|----------------------------------------|---------------|
| tiny      | 10 posts × 5 types = 50                | < 2 s         |
| normal    | 50 × 5 = 250                           | < 10 s        |
| heavy     | 500 × 5 = 2500                         | < 1 min       |
| extreme   | 5000 × 5 = 25000 (perf-test fixture)   | < 10 min      |

Batch DB inserts where feasible to hit these numbers.

---

## Implementation notes

- Location: `src/Fixtures/CLI/ContentSeeder.php` + `src/Fixtures/ContentGenerator.php`
- Depends on #14 (the CPTs). If `AR_DEV_FIXTURES` is off, the command should fail loudly with a clear message instead of seeding into real post types.
- Use `wp_insert_post()` (not raw SQL) so hooks fire — this is what real content does in production, and cleanup plugins need to integrate with that.
- Use `WP_CLI::make_progress_bar` for feedback on large runs.

---

## Out of scope

- Revisions / autosaves / orphans → #16
- The CPTs themselves → #14
- Test plan that consumes these fixtures → #17

---

## References

- [`wp_insert_post`](https://developer.wordpress.org/reference/functions/wp_insert_post/)
- [`wp_insert_user`](https://developer.wordpress.org/reference/functions/wp_insert_user/)
- `WP_CLI::add_command`, `WP_CLI::make_progress_bar`

### LINKED ISSUE #16: Test fixtures: WP-CLI command to seed dummy revisions, autosaves, and orphans
## Goal

WP-CLI command that generates **revision histories** on top of seeded content from #15, with controlled distributions, spread across realistic dates, including autosaves and orphaned revisions. Every cleanup path the plugin builds (#3, #5, #6, #7) needs this to have something meaningful to test against.

Requires: #14 (CPTs) + #15 (content). Fails loudly if `AR_DEV_FIXTURES` is off or no seeded content exists.

---

### `wp advanced-revisions fixtures:revisions [--flags…]`

Generates revisions on every post tagged with the `_ar_seeded` marker (from #15).

| Flag                 | Default   | Meaning                                                                 |
|----------------------|-----------|-------------------------------------------------------------------------|
| `--distribution=`    | `normal`  | `sparse` \| `normal` \| `heavy` \| `extreme` (see table below)         |
| `--seed=N`           | (random)  | RNG seed                                                                |
| `--spread-days=N`    | `1095`    | Revision `post_date` values spread across the last N days               |
| `--autosave-ratio=F` | `0.1`     | Fraction of generated rows that become autosaves instead of revisions   |
| `--orphan-count=N`   | `20`      | Number of orphan revisions to create (parent hard-deleted after)        |
| `--post-types=…`     | (all)     | Comma-separated slugs to target a subset                                |
| `--append`           | off       | Add on top of existing revisions instead of resetting                   |

### Distribution presets

| Name      | Revisions per post | Use case                           |
|-----------|--------------------|------------------------------------|
| `sparse`  | 0–5                | Normal small site                  |
| `normal`  | 1–25               | Typical well-used editorial site   |
| `heavy`   | 10–100             | Old / long-running site            |
| `extreme` | 100–500            | Performance testing (SQL limits)   |

Distribution is applied **per post** via a bounded uniform random in the given range, seeded.

### `wp advanced-revisions fixtures:reset-revisions`

Deletes every revision (and autosave) that this command created — identified by a marker meta (`_ar_seeded_revision => 1`). Never touches unmarked revisions.

### `wp advanced-revisions fixtures:reset-all`

Convenience wrapper: `reset-revisions` + `reset-content` (from #15).

---

## How revisions get generated

For each target post:

1. Determine revision count `R` from the distribution.
2. Generate `R` pairs of (old-content, new-content) by mutating the current post body (swap a word, append a sentence, re-order a block). Keeps diffs visible in core's compare UI.
3. For each pair, call `wp_save_post_revision( $parent_id )` after `wp_update_post()` — matches the real code path.
4. Override the new revision's `post_date` / `post_date_gmt` via a direct `wpdb::update()` to spread it across `--spread-days`. (Core doesn't expose a filter for historical dates — direct UPDATE is intentional for fixtures.)

---

## Autosaves

- Generated with `post_name` matching the core pattern: `{$parent_id}-autosave-v1`.
- One autosave per (user, post) per core's limit — rotate through the test users.
- Count governed by `--autosave-ratio` × total generated rows.

These exercise #8's "hide autosaves" toggle and the autosave-exclusion SQL in #2.

---

## Orphans

- Create `--orphan-count` revisions against newly-seeded throwaway parent posts.
- Immediately `wp_delete_post( $parent, true )` the parent.
- Revisions remain in `wp_posts` with a now-dangling `post_parent`.

These exercise #6 (orphan sweep).

---

## Marker meta

Every seeded revision gets `_ar_seeded_revision => 1`. The reset command matches on this so it can never touch real revisions.

---

## Scale targets

| Scenario  | Posts × revisions                | Approx. rows    | Target       |
|-----------|----------------------------------|-----------------|--------------|
| sparse    | 50 × ~3 = 150                    | 150             | < 5 s        |
| normal    | 50 × ~12 = 600                   | 600             | < 20 s       |
| heavy     | 500 × ~50 = 25,000               | 25k             | < 3 min      |
| extreme   | 500 × ~250 = 125,000             | 125k            | < 15 min     |

Batch inserts via `wpdb::insert` for extreme scales — `wp_save_post_revision` is too slow for 125k rows. Keep both paths available: `--realistic` (goes through `wp_save_post_revision`, slow but accurate) and default (batched inserts, fast but skips some hooks). Default = batched; fixtures care about ending state, not the generation path.

---

## Implementation notes

- Location: `src/Fixtures/CLI/RevisionSeeder.php` + `src/Fixtures/RevisionGenerator.php`
- Progress bar via `WP_CLI::make_progress_bar`
- Sanity guard: refuse to run if `wp_posts` contains more than 10% non-seeded revisions (avoids accidentally nuking real data during reset)

---

## Out of scope

- Content itself → #15
- CPTs → #14
- Test plan consuming these fixtures → #17

---

## References

- [`wp_save_post_revision`](https://developer.wordpress.org/reference/functions/wp_save_post_revision/)
- [`wp_create_post_autosave`](https://developer.wordpress.org/reference/functions/wp_create_post_autosave/)
- [`wp_delete_post`](https://developer.wordpress.org/reference/functions/wp_delete_post/)

### LINKED ISSUE #17: Test plan: coverage matrix, scenarios, and runbook
## Goal

Produce a **test plan document** (living in `docs/testing.md`) that defines:

- How each feature is tested at each level (unit / integration / E2E)
- Named **fixture scenarios** that reproduce specific states (tiny site, heavy site, orphan-heavy, autosave-flood, multi-author, etc.) via the `fixtures:*` WP-CLI commands from #14–#16
- Local runbook (DDEV) and CI matrix
- How a contributor bootstraps fresh fixtures for an E2E run

Blocked by #14, #15, #16 — the plan references their commands.

---

## Deliverable

A single markdown file at `docs/testing.md` with the structure below, plus any supporting scripts under `bin/test-*`.

---

## 1. Philosophy (≤ 1 page)

- **Unit** (Brain Monkey, `tests/Unit/`): pure logic only — nothing that hits `wp_posts`. Hook registration, value transforms, config parsing, the `ProtectionService::filter_deletable()` calculation.
- **Integration** (`tests/Integration/`, real WP + MySQL): anything that touches the database or a WP function with meaningful side effects. This is the primary coverage layer for revision manipulation.
- **E2E** (Playwright, `e2e/`): admin screens — settings page, overview, row actions, bulk actions, compare screen, tag management. Real browser, real clicks.

Decision rule: if it touches `wp_posts`, it goes in integration. If it renders an admin screen, it goes in E2E.

---

## 2. Running tests locally (DDEV)

```bash
ddev start && ddev orchestrate

# Unit
ddev composer test:unit

# Integration (seeds fixtures automatically via a setUp hook)
ddev composer test:integration

# E2E
ddev wp advanced-revisions fixtures:content --count=50 --seed=42
ddev wp advanced-revisions fixtures:revisions --distribution=normal --seed=42
npm run test:e2e
```

---

## 3. Coverage matrix

One row per feature issue. Populate as features land.

| Feature | Unit | Integration | E2E | Fixture scenario |
|---------|:----:|:-----------:|:---:|------------------|
| #1 Per-type limit                | ✓ | ✓ | ✓ | `mixed-types`    |
| #2 Overview list table           | — | ✓ | ✓ | `heavy-site`     |
| #3 Bulk delete                   | ✓ | ✓ | ✓ | `heavy-site`     |
| #4 Post list column              | — | ✓ | ✓ | `normal-site`    |
| #5 Scheduled cleanup             | ✓ | ✓ | — | `orphan-heavy`, `age-spread`|
| #6 Orphan sweep                  | — | ✓ | — | `orphan-heavy`   |
| #7 WP-CLI                        | ✓ | ✓ | — | `heavy-site`     |
| #8 Autosave separation           | ✓ | ✓ | ✓ | `autosave-flood` |
| #9 Post-meta revisioning         | ✓ | ✓ | ✓ | `product-meta`   |
| #10 Dashboard widget             | — | ✓ | ✓ | `normal-site`    |
| #11 Per-post override            | ✓ | ✓ | ✓ | `mixed-types`    |
| #12 Arbitrary compare            | — | ✓ | ✓ | `normal-site`    |
| #13 Tagging + protection         | ✓ | ✓ | ✓ | `tagged-site`    |

E2E cells marked `—` are features without an admin-screen surface; their CLI/cron paths stay in integration.

---

## 4. Fixture scenarios

Each scenario is a **named recipe** of `fixtures:*` flags. Used by docs, manual testing, and E2E setup.

| Scenario         | Content                               | Revisions                                                   |
|------------------|---------------------------------------|-------------------------------------------------------------|
| `tiny-site`      | `content --count=10`                  | `revisions --distribution=sparse`                           |
| `normal-site`    | `content --count=50`                  | `revisions --distribution=normal`                           |
| `heavy-site`     | `content --count=500`                 | `revisions --distribution=heavy`                            |
| `mixed-types`    | `content --count=20 --post-types=ar_test_article,ar_test_product,ar_test_note` | `revisions --distribution=normal` |
| `orphan-heavy`   | `content --count=50`                  | `revisions --distribution=normal --orphan-count=200`        |
| `autosave-flood` | `content --count=50`                  | `revisions --distribution=normal --autosave-ratio=0.5`      |
| `age-spread`     | `content --count=50 --date-spread=2190` | `revisions --distribution=normal --spread-days=2190`      |
| `multi-author`   | `content --count=50 --authors=10`     | `revisions --distribution=normal`                           |
| `product-meta`   | `content --count=30 --post-types=ar_test_product` | `revisions --distribution=normal`              |
| `tagged-site`    | `content --count=30`                  | `revisions --distribution=normal` + seeded tags (see #13)   |
| `extreme-perf`   | `content --count=5000`                | `revisions --distribution=extreme`                          |

All use `--seed=42` by default for reproducibility. CI overrides with a per-job seed.

Provide a convenience command:

```bash
wp advanced-revisions fixtures:scenario tagged-site [--seed=N] [--force]
```

which chains the content + revisions commands with the right flags. This belongs to the same code as #15 / #16.

---

## 5. E2E playbook

For each Playwright spec:

1. `global-setup.js` enables `AR_DEV_FIXTURES` via a must-use plugin dropped into `.ddev/wordpress/wp-content/mu-plugins/`.
2. Per-suite `beforeAll`: call `wp advanced-revisions fixtures:reset-all` then `fixtures:scenario $NAME`.
3. Auth state handled by existing `e2e/auth.setup.js`.
4. Teardown: none. Fixtures are per-run, not per-test.

Document the per-scenario URL entrypoints so specs know where to navigate.

---

## 6. CI reference

| Workflow            | Trigger            | Tests                                        |
|---------------------|--------------------|----------------------------------------------|
| `ci.yml`            | PR, push to main   | PHPCS, PHPStan, unit tests (PHP 8.1–8.4)     |
| `integration.yml`   | PR, push to main   | Integration tests, multisite matrix          |
| `e2e.yml`           | PR, push to main   | Playwright against live WP + seeded scenarios |
| `wp-beta.yml`       | Nightly            | Integration against WP beta/RC               |

Each job runs `fixtures:reset-all` then the scenario it needs. Jobs that need different scenarios run in parallel; they don't share DB state.

---

## 7. Gaps this plan doesn't cover (yet)

- Visual regression / screenshot diffing for the overview table
- Load testing beyond 125k revisions
- Accessibility testing (may add to E2E via `@axe-core/playwright`)

Tracked separately if/when needed.

---

## Implementation order

1. Create `docs/testing.md` with sections 1–7, populated from this issue.
2. Add `fixtures:scenario` wrapper command (shared with #15/#16).
3. Wire `e2e/global-setup.js` to activate `AR_DEV_FIXTURES`.
4. For each feature issue that lands, update the coverage matrix row.

The matrix should always reflect what's *actually* covered — when a feature ships without E2E, mark it with `—` explicitly rather than leaving the cell empty.

### LINKED ISSUE #19: Remove obsolete phpcs:ignore for wp_delete_post after coding-standards update
## Summary

A `phpcs:ignore Apermo.WordPress.RequireWpErrorHandling.Unchecked` comment was added to suppress a false-positive warning on a `wp_delete_post()` call. Upstream fix is tracked in apermo/apermo-coding-standards#95 — once that ships and this repo bumps `apermo/apermo-coding-standards`, the suppression can be removed.

## Background

`wp_delete_post()` is typed `WP_Post|false|null` in WordPress core — it never returns `WP_Error`, so `is_wp_error()` on its result is meaningless. The sniff incorrectly listed it in its WP_Error allow-list; that is being fixed upstream.

## Action

After updating the `apermo/apermo-coding-standards` dependency to the release containing apermo/apermo-coding-standards#95:

1. Locate the `// phpcs:ignore Apermo.WordPress.RequireWpErrorHandling.Unchecked -- wp_delete_post() is typed WP_Post|false|null, not WP_Error.` line in the `wp_delete_post()` call site.
2. Remove that line (the suppression and its explanatory suffix).
3. Run `composer phpcs` (or equivalent) to confirm no warning is emitted.

### LINKED ISSUE #20: Remove obsolete phpcs:ignore for NoHardcodedTableNames on <table> HTML
## Summary

A `phpcs:ignore Apermo.WordPress.NoHardcodedTableNames.Found` comment was added to suppress a false-positive warning on an HTML `<table class=...>` echo. Upstream fix is apermo/apermo-coding-standards#101 — once that ships and this repo bumps `apermo/apermo-coding-standards`, the suppression can be removed.

## Background

The sniff's original regex treated `TABLE` as a standalone SQL keyword and matched `<table class="wp-list-table …">` HTML as if `class` were a hardcoded table name. The upstream fix scopes `TABLE` to DDL verbs (`CREATE`, `DROP`, `ALTER`, `TRUNCATE`, `RENAME`), so HTML no longer triggers.

## Action

After updating the `apermo/apermo-coding-standards` dependency to the release containing apermo/apermo-coding-standards#101:

1. Locate the `// phpcs:ignore Apermo.WordPress.NoHardcodedTableNames.Found -- CSS class names on an HTML element, not SQL.` line on the `echo '<table class="wp-list-table widefat fixed striped">';` call site.
2. Remove that line (the suppression and its explanatory suffix).
3. Run `composer phpcs` (or equivalent) to confirm no warning is emitted.
4. Grep the codebase for any other `phpcs:ignore Apermo.WordPress.NoHardcodedTableNames.Found` comments on `<table ...>` lines and remove those too.

### LINKED ISSUE #21: Audit and remove obsolete Apermo phpcs:ignore markers after coding-standards bump
## Summary

PR #18 carries ~18 `phpcs:ignore`/`phpcs:disable` markers referencing `Apermo.*` sniffs. After reviewing upstream sniff state, the majority are **obsolete** — either already fixed upstream, or defensive for warnings that never actually fire. This issue tracks the consolidated cleanup once `apermo/apermo-coding-standards` is bumped to the next release (which ships apermo/apermo-coding-standards#95, #101, #102).

This supersedes the narrower scope of #19 and #20; those can be closed in favour of this audit.

## Removals — no upstream dep bump required (defensive / never-fired ignores)

These reference sniff behavior that has never produced a warning on these call sites. Safe to remove now:

- `src/Revisions/RevisionDeleter.php:53`
  `phpcs:ignore Apermo.WordPress.RequireWpErrorHandling.Unchecked` on `wp_delete_post_revision()`.
  `wp_delete_post_revision` has never been in the sniff's `WP_ERROR_FUNCTIONS` allow-list — exact match on function names means it cannot fire.

- `advanced-revisions-dev/src/Fixtures/RevisionSeeder.php:167`
  Same as above — `wp_delete_post_revision()`.

- `advanced-revisions-dev/src/Fixtures/RevisionGenerator.php:7`
  File-level `phpcs:disable Apermo.WordPress.NoHardcodedTableNames.Found`. No strings in the file contain the `FROM`/`JOIN`/`INTO`/`UPDATE`/`TABLE` sequences the sniff looks for. Disable is a no-op.

### `Apermo.WordPress.RequireWpErrorHandling.Unchecked`

- `advanced-revisions-dev/src/Fixtures/ContentSeeder.php:117`
  `wp_delete_post()` — apermo/apermo-coding-standards#95 removed it from the sniff's allow-list.

### `Apermo.WordPress.NoHardcodedTableNames.Found`

All obsolete after apermo/apermo-coding-standards#101 (DDL-scoped `TABLE`) + apermo/apermo-coding-standards#102 (SQL-context gate on the other anchors):

- `src/Admin/OverviewPage.php:176` — `<table class=\"…\">` HTML.
- `advanced-revisions-dev/src/Fixtures/ContentGenerator.php:7` — file-level disable for vocabulary strings (e.g. `'lessons from a team'`, `'from the admin'`).
- `src/Revisions/TaxonomyRegistrar.php:88` — UI labels (`'Update Revision Tag'`).

### `Apermo.DataStructures.ArrayComplexity.TooManyKeys`

Twelve call sites. Every audited array has ≤9 top-level keys; the 2.8.0 `warnKeys=10` default (raised from 5) no longer flags any of them:

- `advanced-revisions-dev/src/CLI/FixturesCommand.php` — lines 236, 275, 310
- `advanced-revisions-dev/src/Fixtures/ContentSeeder.php` — lines 100, 145
- `advanced-revisions-dev/src/Fixtures/RevisionSeeder.php` — lines 150, 195, 231
- `advanced-revisions-dev/src/Fixtures/ContentGenerator.php` — line 56
- `advanced-revisions-dev/src/TestPostTypes.php` — line 119
- `src/Revisions/TaxonomyRegistrar.php` — lines 35, 89
- `src/Revisions/RevisionRepository.php` — line 68

## Action

1. Wait for `apermo/apermo-coding-standards` 2.8.0 (or equivalent) tag.
2. Bump the dep in `composer.json` + `composer.lock`.
3. Remove the `defensive / never-fired` markers listed above now (independent of the bump).
4. After the bump, remove the rest.
5. Run `composer phpcs` — expected: zero Apermo errors/warnings across `src/` and `advanced-revisions-dev/src/`.
6. Close #19, #20 as subsumed by this issue.

### PR DESCRIPTION
**Pull request by apermo**
## Closes

Closes #1, closes #2, closes #3, closes #4, closes #10, closes #11, closes #13, closes #14, closes #15, closes #16, closes #17, closes #19, closes #20, closes #21

## Summary

Implements the v0.1.0 milestone (11 issues) plus three coding-standards cleanup items (#19, #20, #21) made obsolete by the `apermo/apermo-coding-standards` 2.8.0 / 2.9.0 bumps that landed on this branch.

Intentionally broken up into atomic commits — each commit maps to one concern and can be reviewed independently.

## Progress

| Commit            | Theme                                                                               |
| ----------------- | ----------------------------------------------------------------------------------- |
| `c34c7eb`         | #14 Dev fixtures plugin with test CPTs                                              |
| `7db3c3a`         | #15 WP-CLI seed dummy content                                                       |
| `58c00ee`         | #16 WP-CLI seed dummy revisions                                                     |
| `429a60a`         | #1 Per-type revision limit                                                          |
| `da0ff60`         | #4 Post list column                                                                 |
| `49da4fd`         | #13 Tagging + protection (foundation)                                               |
| `f9a79eb`         | #10 Dashboard widget                                                                |
| `b5031f8`         | #11 Per-post override                                                               |
| `badb260`         | #2 + #3 Admin overview + bulk revision deletion                                     |
| `ae50e58`         | #17 Test plan doc                                                                   |
| `ecd720f`         | CI + review-comment fixes (bootstrap stub ordering, PHPStan memory, compare_url, capability, ProtectionService, seeder determinism, …) |
| `6dfb140`         | +33 unit tests to clear the 80% Codecov threshold                                   |
| `ba6c523`         | perf: scope PostListColumn SQL to the current screen                                |
| `1dbd63d`         | perf: batch ProtectionService term queries                                          |
| `c67afcb`         | #19 + #20 + #21 Drop inline PHPCS ignores obsoleted by standards 2.8.0              |
| `9733ab7`+`2c58545` | Coding-standards bumps to ^2.8 then ^2.9                                          |
| `b266bb7`         | `total_parents()` paginator denominator alignment + `ONLY_FULL_GROUP_BY` portability |
| `103d9d8`         | Dashboard `compute()` excludes autosaves + portable GROUP BY                        |
| `d476c34`         | Dashboard i18n via `_n()` + `wp_kses()` (plural-correct, full sentences)            |
| `dbf5228`         | PostListColumn `compare_url()` batching — eliminates per-row N+1                    |
| `702d995`         | ProtectionService termmeta priming — completes the N+1 batching line                |
| `6b1ca62`         | Meta-cap refactor: `delete_others_posts` + filterable + per-parent `edit_post` + `exit()` after redirects + widened `auth_callback` |
| `a4c7801`         | Screen-reader labels for overview select-all and row checkboxes                     |
| `45530cd`         | `wp_loaded` priority so metabox registration picks up late-registered CPTs          |
| `e82989e`         | README + CHANGELOG refresh for release                                              |

## Test plan

- [x] PHPCS (apermo-coding-standards 2.9.0) clean across `src/` and `advanced-revisions-dev/`
- [x] PHPStan (level 6) clean
- [x] 122 unit tests, 1016 assertions — all passing
- [x] Integration suite: 8 jobs (PHP 8.2/8.4 × WP 6.4/latest × single/multisite) all pass
- [x] E2E (`wp-env`) passing
- [x] Codecov patch + project checks passing (≈82% line coverage on `src/`)
- [x] `git archive HEAD | tar t` confirms `advanced-revisions-dev/` is NOT in the distribution

## Scope decisions worth flagging

- **#13 tagging** ships the foundation (taxonomy + term meta + `ProtectionService`). Sidebar panel + retroactive-tag metabox UI are deferred.
- **#2 + #3** combined — overview without bulk delete is half-baked. Uses a plain HTML table (not `WP_List_Table`) to keep it unit-testable. `WP_List_Table` upgrade is a follow-up.
- **Integration + E2E coverage matrix** rows in `docs/testing.md` are marked `—` (intentionally not covered at this layer) for v0.1.0. Infrastructure is in place; per-feature integration/E2E tests land as follow-ups.

## Review pointers

- Code review: click the **Commits** tab and walk top-to-bottom. Each commit stands on its own.
- Foundational commits (#14, #15, #16, #17) set up dev tooling; no production plugin behavior.
- Feature commits add one user-facing capability each.
- Trailing commits are the code-review response round: correctness fixes, perf batching, portability hardening, a11y labels, doc refresh.

### CODE REVIEW

**Comment by apermo** [comment]
### CI + review-comment pass

Addressed every CI check + most of the inline review comments.

**CI fixes:**
- `ci / PHPStan` — bumped memory limit from 512M → 1G (was crashing mid-analysis)
- `pr-validation / validate` — deleted the stale `v0.1.0` remote tag (the release had been deleted but the tag lingered, making the version look "already tagged")
- `integration / *` — `tests/bootstrap.php` now loads WP class stubs only when no real WP test suite is available (previously caused `Cannot redeclare WP_User` fatal in every integration job)
- `e2e / WP latest` — added `.wp-env.json` so the reusable e2e workflow can boot WordPress

**Code review (fixed):**
- `PostListColumn::compare_url()` now resolves the latest revision ID instead of passing the parent post ID to `revision.php?from=&to=` (which was invalid)
- `PostListColumn::load_counts()` now scopes the aggregation to the current screen's post IDs from `$wp_query->posts` instead of aggregating across every revision site-wide
- `RevisionRepository::revision_ids_for_parents()` excludes autosaves so bulk-delete counts match what the overview shows
- `RevisionLimitMetaBox` uses the `edit_post` meta cap with `$post_id` instead of the flat `edit_others_posts` primitive (fixes authorization for pages and custom post types)
- `OverviewPage::handle_bulk_post()` calls `DashboardWidget::flush()` after a successful delete so the cached stats refresh
- `ProtectionService` batches term-meta priming and uses `array_flip` for O(1) protected-id lookups (was O(n*m) with `in_array`)
- `ContentSeeder` + `RevisionSeeder` accept an optional `now` anchor so `--seed=N` produces fully-reproducible timestamps
- `tests/bootstrap.php` stub-loading ordering fix (as noted above)

**Coverage:**
- Line coverage: 36% → ~84% on `src/`
- Added `tests/Fixtures/WpdbDouble.php` so SQL-executing code can be unit-tested without a real DB
- 33 new unit tests (88 → 121 total; 967 → 1017 assertions)

**Still open (noted for follow-up, not blocking):**
- WP-CLI command namespace `wp ar-fixtures` vs spec `wp advanced-revisions fixtures:*` — consistency between dev plugin and issue docs to resolve

File: advanced-revisions-dev/advanced-revisions-dev.php [hunk 1]
```diff
@@ -0,0 +1,38 @@
+<?php
+/**
+ * Plugin Name: Advanced Revisions – Dev Fixtures
+ * Description: Test custom post types and seed WP-CLI commands for developing
+ *              Advanced Revisions. DO NOT INSTALL IN PRODUCTION.
+ * Version:     0.1.0
+ * Requires PHP: 8.1
+ * License:     GPL-2.0-or-later
+ */
```
Comment (apermo) [inline advanced-revisions-dev/advanced-revisions-dev.php]: aligment

File: advanced-revisions-dev/src/Fixtures/ContentSeeder.php [hunk 2]
```diff
@@ -0,0 +1,165 @@
...
+				update_post_meta( $post_id, Marker::SEEDED_POST, Marker::YES );
+				$totals[ $post_type ]++;
+			}
+		}
+
+		return $totals;
+	}
+
+	/**
+	 * Delete every post (and its revisions) that was created by the seeder.
```
Comment (apermo) [inline advanced-revisions-dev/src/Fixtures/ContentSeeder.php]: PHPDoc Comments should be in "(The function) Deletes" style, will apply to all comments.

File: advanced-revisions-dev/src/Fixtures/ContentSeeder.php [hunk 3]
```diff
@@ -0,0 +1,165 @@
...
+	 *
+	 * @return int Number of parent posts deleted.
+	 */
+	public function reset(): int {
+		$query = new WP_Query(
+			// phpcs:ignore Apermo.DataStructures.ArrayComplexity.TooManyKeys -- WP_Query args are a WP API shape.
```
Comment (apermo) [inline advanced-revisions-dev/src/Fixtures/ContentSeeder.php]: Noted for fixing in coding standards, create an issue to review when updating the coding standards next time.

File: src/Admin/DashboardWidget.php [hunk 4]
```diff
@@ -0,0 +1,180 @@
...
+ * notice it without visiting a dedicated page.
+ *
+ * Stats are expensive to compute on sites with millions of revisions, so
+ * they're cached in a transient keyed on {@see self::TRANSIENT_KEY}.
+ */
+final class DashboardWidget {
+
+	public const WIDGET_ID     = 'advanced_revisions_dashboard';
+	public const TRANSIENT_KEY = 'advanced_revisions_dashboard_stats';
+	public const CAPABILITY    = 'edit_others_posts';
```
Comment (apermo) [inline src/Admin/DashboardWidget.php]: name should be more self explanatory, not neccessarily the actual capability, but in the direction, this made me scroll up to see whats in

File: src/Admin/DashboardWidget.php [hunk 5]
```diff
@@ -0,0 +1,180 @@
...
+	}
+
+	/**
+	 * Renders the widget body.
+	 */
+	public static function render(): void {
+		$stats = self::stats();
+
+		if ( $stats['total'] === 0 ) {
+			echo '<p>' . esc_html__( 'No stored revisions. You are clean.', 'advanced-revisions' ) . '</p>';
```
Comment (apermo) [inline src/Admin/DashboardWidget.php]:
```suggestion
			echo '<p>' . esc_html__( 'No stored revisions.', 'advanced-revisions' ) . '</p>';
```

File: src/Admin/PostListColumn.php [hunk 6]
```diff
@@ -0,0 +1,272 @@
...
+				WHERE post_type = 'revision'
+					AND post_parent IN (%s)
+					AND post_name NOT LIKE CONCAT(post_parent, '-autosave-%%')
+				GROUP BY post_parent",
+			$placeholders,
+		);
+
+		// phpcs:disable WordPress.DB.DirectDatabaseQuery,WordPress.DB.PreparedSQL,WordPress.DB.PreparedSQLPlaceholders -- scoped to trusted int IDs from the main query.
+		$rows = $wpdb->get_results( $wpdb->prepare( $query, ...$post_ids ) );
+		// phpcs:enable
```
Comment (apermo) [inline src/Admin/PostListColumn.php]: there is a better approach for this

File: src/Revisions/RevisionRepository.php [hunk 7]
```diff
@@ -0,0 +1,137 @@
...
+				WHERE post_type = 'revision'
+				AND post_parent IN (%s)
+				AND post_name NOT LIKE CONCAT(post_parent, '-autosave-%%')",
+			$placeholders,
+		);
+
+		// phpcs:ignore WordPress.DB.DirectDatabaseQuery,WordPress.DB.PreparedSQL.InterpolatedNotPrepared,WordPress.DB.PreparedSQL.NotPrepared,WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare -- placeholders built above from a fixed count of trusted int IDs; values passed through wpdb::prepare.
+		$ids = $wpdb->get_col(
+			$wpdb->prepare( $query, ...$parent_ids ), // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
+		);
```
Comment (apermo) [inline src/Revisions/RevisionRepository.php]: there is a better approach to this

File: advanced-revisions-dev/advanced-revisions-dev.php [hunk 8]
```diff
@@ -0,0 +1,38 @@
...
+			require $path;
+		}
+	},
+);
+
+add_action( 'init', [ TestPostTypes::class, 'register' ] );
+
+if ( \defined( 'WP_CLI' ) && \WP_CLI ) {
+	WP_CLI::add_command( 'ar-fixtures', CLI\FixturesCommand::class );
+}
```
[the remark this answers is not in the document]
Comment (apermo) [reply advanced-revisions-dev/advanced-revisions-dev.php:38]: Checked the repo: all docs (`docs/testing.md`, `CHANGELOG.md`) and code consistently use `wp ar-fixtures …`. The colon-namespaced form `wp advanced-revisions fixtures:*` from the original spec isn't idiomatic WP-CLI — WP-CLI uses space-separated groups (`wp plugin list`), not colon-subcommands.

Keeping `ar-fixtures`: short, WP-CLI-idiomatic, and matches the dev plugin's namespace prefix. Updated the "Open from review" note in the PR body accordingly.

File: advanced-revisions-dev/advanced-revisions-dev.php (hunk 1 above)
Comment (apermo) [reply advanced-revisions-dev/advanced-revisions-dev.php]: Fixed in d062a83 — all header values now align on column 18 (padded to match the longest field name, `Requires PHP:`).

File: advanced-revisions-dev/src/Fixtures/ContentSeeder.php (hunk 2 above)
Comment (apermo) [reply advanced-revisions-dev/src/Fixtures/ContentSeeder.php]: Applied across the codebase — the `Apermo.Commenting.DocSummaryStyle` sniff in coding-standards 2.8.0 now enforces third-person singular summaries automatically. Fixes landed in 645a87e, 1a89731, c67afcb, and 5f9af2e.

File: advanced-revisions-dev/src/Fixtures/ContentSeeder.php (hunk 3 above)
Comment (apermo) [reply advanced-revisions-dev/src/Fixtures/ContentSeeder.php]: Coding-standards 2.8.0 shipped the ArrayComplexity threshold tuning (milestone issue #97), so this ignore is obsolete. Bumped the dependency to `^2.8` in 9733ab7 and dropped this ignore plus 15 others across the codebase + the `*/tests/*` exclusion in `phpcs.xml.dist` in c67afcb.

File: src/Admin/DashboardWidget.php (hunk 4 above)
Comment (apermo) [reply src/Admin/DashboardWidget.php]: Renamed to `REQUIRED_CAPABILITY` in 5f9af2e, applied consistently across `DashboardWidget`, `OverviewPage`, `SettingsPage`, and the matching unit tests.

File: src/Admin/DashboardWidget.php (hunk 5 above)
Comment (apermo) [reply src/Admin/DashboardWidget.php]: Applied in 564f9dc.

File: src/Admin/PostListColumn.php (hunk 6 above)
Comment (apermo) [reply src/Admin/PostListColumn.php]: This path was substantially refactored after the original review — ba6c523 scoped the SQL to the current admin screen via `$wp_query->posts` (instead of aggregating site-wide), and 206e044 switched to `%i` identifier placeholders with array args. Current code: `src/Admin/PostListColumn.php:196-241`.

Resolving — if a different approach is still in mind, please reopen.

File: src/Revisions/RevisionRepository.php (hunk 7 above)
Comment (apermo) [reply src/Revisions/RevisionRepository.php]: Same refactor as the `PostListColumn` path: 206e044 switched to `%i` identifier placeholders with array args. Queries for `paginated()`, `total_parents()`, and `revision_ids_for_parents()` are now prepared with explicit arg arrays for the post_parent `IN (...)` expansion and the autosave `LIKE` pattern.

Resolving — if a different approach is in mind, please reopen.

File: src/Revisions/RevisionRepository.php [hunk 9]
```diff
@@ -0,0 +1,153 @@
...
+				'oldest_gmt' => (string) $row_data->oldest_gmt,
+			];
+		}
+		return $result;
+	}
+
+	/**
+	 * Counts parent posts with at least one revision — used for paginator.
+	 */
+	public function total_parents(): int {
```
Comment (apermo) [inline src/Revisions/RevisionRepository.php:107]: 🟡 **Paginator denominator mismatch.** `total_parents()` doesn't filter by `post_status`, but `paginated()` (line 54) restricts to `('publish','draft','pending','private','future')`. Parents in `trash`/`auto-draft`/`inherit` are counted in the denominator → the paginator can report more pages than `paginated()` will ever return, yielding empty "Next »" pages.

Suggest factoring the status list into a shared constant and applying it in both queries:

```php
private const OVERVIEW_STATUSES = [ 'publish', 'draft', 'pending', 'private', 'future' ];
```

Then join on `$wpdb->posts` in `total_parents()` with the same `WHERE` clause.

File: src/Revisions/RevisionRepository.php [hunk 10]
```diff
@@ -0,0 +1,153 @@
...
+		global $wpdb;
+		if ( ! isset( $wpdb ) || $parent_ids === [] ) {
+			return [];
+		}
+
+		$placeholders = \implode( ', ', \array_fill( 0, \count( $parent_ids ), '%d' ) );
+		// Literal LIKE pattern; no user input to escape.
+		$autosave_like = '-autosave-%';
+
+		// phpcs:disable WordPress.DB.DirectDatabaseQuery,WordPress.DB.PreparedSQL.InterpolatedNotPrepared,WordPress.DB.PreparedSQLPlaceholders.ReplacementsWrongNumber -- {$placeholders} is a fixed %d repeater; merged args feed wpdb::prepare.
```
Comment (apermo) [inline src/Revisions/RevisionRepository.php:154]: 🟡 **Duplicated `{$placeholders}` repeater pattern.** The same `implode + array_fill + phpcs:disable block + array_merge` appears verbatim in `src/Admin/PostListColumn.php:207`. Extracting a tiny helper would DRY this up and move the single `phpcs:disable` annotation into one place:

```php
private static function in_placeholders(int $count): string {
    return \implode(', ', \array_fill(0, $count, '%d'));
}
```

File: src/Admin/OverviewPage.php [hunk 11]
```diff
@@ -0,0 +1,291 @@
...
+
+/**
+ * Tools → Revisions page. Lists posts with stored revisions and lets admins
+ * bulk-delete revisions across selected rows. Protected tags (from #13) are
+ * honored via {@see RevisionDeleter}.
+ */
+final class OverviewPage {
+
+	public const MENU_SLUG           = 'advanced-revisions-overview';
+	public const REQUIRED_CAPABILITY = 'edit_others_posts';
```
Comment (apermo) [inline src/Admin/OverviewPage.php]: 🟡 **Destructive op gated at Editor level.** `edit_others_posts` is granted to Editors, but this constant gates a cross-author bulk destructive operation. `delete_others_posts` would be more aligned with least-privilege for destructive cross-user operations — or at minimum, make this filterable so sites with custom role maps can narrow it:

```php
public static function required_capability(): string {
    return (string) apply_filters( 'advanced_revisions_bulk_delete_capability', 'delete_others_posts' );
}
```

File: src/Admin/OverviewPage.php [hunk 12]
```diff
@@ -0,0 +1,291 @@
...
+		if ( $selected === [] ) {
+			wp_safe_redirect( self::page_url( [ 'ar_bulk' => 'empty' ] ) );
+			return;
+		}
+
+		$deleter = new RevisionDeleter( new RevisionRepository() );
+		$result  = $deleter->delete_for_parents( $selected );
+
+		// Invalidate aggregate caches so the dashboard widget reflects reality.
+		DashboardWidget::flush();
```
Comment (apermo) [inline src/Admin/OverviewPage.php:152]: 🟡 **Widget cache only flushed on bulk-delete.** `DashboardWidget::flush()` is called here, but core's `wp_revisions_to_keep` pruning (runs on every save when a limit is configured) doesn't flush. With the 1-hour transient TTL, the widget can show a stale count for up to an hour after normal editorial activity.

Suggest hooking `deleted_post` (with `get_post_type( $id ) === 'revision'` guard) in `DashboardWidget::register()`:

```php
add_action( 'deleted_post', [ self::class, 'maybe_flush_on_revision_delete' ], 10, 2 );
```

**Review by apermo — COMMENTED** [review]
Independent review pass on the production code under `src/` (1710 lines, 11 files).

**Verdict:** Ship with one correctness follow-up (paginator denominator mismatch in `RevisionRepository::total_parents`) and a handful of should-fixes. **No blockers, no security holes.** SQL is well-parameterized, admin entry points are capability-gated, nonces verified.

**What's notably well done**
- Consistent `%i` identifier placeholder across every `$wpdb->prepare()`.
- `ProtectionService::terms_by_revision` dodges N+1 via `all_with_object_id`.
- `PostListColumn` scoped to `$wp_query->posts` instead of the whole table.
- Nonce + capability + unslash/sanitize triad on `handle_bulk_post` and metabox `save` is textbook.
- All service classes `final`, stateless, no surprise globals (one per-request static cache in `PostListColumn` with test-only `reset_cache`).

Findings below — 5 🟡 should-fix, 6 🟢 nits.

File: src/Admin/OverviewPage.php [hunk 13]
```diff
@@ -0,0 +1,291 @@
...
+
+		if ( $state === 'done' ) {
+			// phpcs:ignore WordPress.Security.NonceVerification.Recommended
+			$deleted = isset( $_GET['ar_deleted'] ) ? (int) $_GET['ar_deleted'] : 0;
+			// phpcs:ignore WordPress.Security.NonceVerification.Recommended
+			$skipped = isset( $_GET['ar_skipped'] ) ? (int) $_GET['ar_skipped'] : 0;
+
+			$message = \sprintf(
+				/* translators: 1: deleted count, 2: skipped count */
+				esc_html__( 'Deleted %1$d revisions. %2$d protected revisions were skipped.', 'advanced-revisions' ),
```
Comment (apermo) [inline src/Admin/OverviewPage.php]: 🟡 **`wp_admin_notice` escaping footgun.** `wp_admin_notice()` does NOT escape its first argument — it's rendered as HTML (see `wp-includes/functions.php`). `esc_html__()` on the format string doesn't protect interpolated values. Integers are safe today, but if someone adds a `%s` (e.g. the author name) tomorrow, this becomes an XSS vector.

Build the message from pieces, escaping at the point of interpolation:

```php
$message = sprintf(
    /* translators: ... */
    esc_html__( 'Deleted %1$d revisions. %2$d protected revisions were skipped.', 'advanced-revisions' ),
    (int) $deleted,
    (int) $skipped,
);
```

Or pre-escape each variable with `esc_html()` before interpolation.

File: src/Revisions/RevisionDeleter.php [hunk 14]
```diff
@@ -0,0 +1,66 @@
...
+	/**
+	 * Deletes every unprotected revision belonging to the given parent posts.
+	 *
+	 * @param array<int, int> $parent_ids Parent post IDs.
+	 * @return array{deleted:int, skipped:int}
+	 */
+	public function delete_for_parents( array $parent_ids ): array {
+		$revision_ids = $this->repository->revision_ids_for_parents( $parent_ids );
+		$deletable    = ProtectionService::filter_deletable( $revision_ids );
+		$protected    = \count( $revision_ids ) - \count( $deletable );
```
Comment (apermo) [inline src/Revisions/RevisionDeleter.php]: 🟢 `$protected = count($revision_ids) - count($deletable)` avoids a second `terms_by_revision` call that `ProtectionService::count_protected()` would trigger. One-line comment (`// Arithmetic avoids a second term-fetch vs. count_protected().`) would prevent a future "simplification" regression.

File: src/Admin/RevisionLimitMetaBox.php [hunk 15]
```diff
@@ -0,0 +1,156 @@
...
+		add_action( 'add_meta_boxes', [ self::class, 'add_meta_box' ] );
+		add_action( 'save_post', [ self::class, 'save' ], 10, 2 );
+		add_action( 'init', [ self::class, 'register_post_meta' ] );
+	}
+
+	/**
+	 * Exposes the override meta to REST so block-editor clients can manage it.
+	 */
+	public static function register_post_meta(): void {
+		foreach ( self::revisable_post_types() as $post_type ) {
```
Comment (apermo) [inline src/Admin/RevisionLimitMetaBox.php:40]: 🟢 **Init-priority ordering.** `revisable_post_types()` calls `get_post_types()` during `add_meta_boxes` → `init` chain. CPTs registered on `init` with priority ≥10 won't appear. Defer the metabox registration to `wp_loaded` or bump `add_meta_boxes` priority if this hits plugins that register CPTs late.

File: src/Admin/PostListColumn.php [hunk 16]
```diff
@@ -0,0 +1,279 @@
...
+		return $counts;
+	}
+
+	/**
+	 * Extracts post IDs from the main $wp_query's current page of results.
+	 *
+	 * @param mixed $wp_query Global $wp_query reference (WP_Query or null).
+	 * @return array<int, int>
+	 */
+	private static function current_screen_post_ids( mixed $wp_query ): array {
```
Comment (apermo) [inline src/Admin/PostListColumn.php]: 🟢 **`mixed` type reads oddly.** Caller passes `$wp_query ?? null`; the function immediately narrows via `is_object(...) && isset(...)`. Typing as `?\WP_Query` with `$wp_query instanceof \WP_Query` reads as clearly and gives static analysers more signal:

```php
private static function current_screen_post_ids( ?\WP_Query $wp_query ): array {
    if ( ! $wp_query instanceof \WP_Query || ! is_array( $wp_query->posts ) ) {
        return [];
    }
    ...
```

File: src/Admin/OverviewPage.php [hunk 17]
```diff
@@ -0,0 +1,291 @@
...
+	/**
+	 * Renders completion notices after a bulk action redirects back.
+	 */
+	private static function render_notices(): void {
+		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- notice state parsed from query args after redirect.
+		if ( ! isset( $_GET['ar_bulk'] ) ) {
+			return;
+		}
+		// phpcs:ignore WordPress.Security.NonceVerification.Recommended
+		$state = \is_string( $_GET['ar_bulk'] ) ? sanitize_key( $_GET['ar_bulk'] ) : '';
```
Comment (apermo) [inline src/Admin/OverviewPage.php]: 🟢 **Missing `wp_unslash()` before `sanitize_key()`.** Functionally safe (`sanitize_key` strips non-`[a-z0-9_-]`) but breaks the unslash+sanitize pattern used on line 85. Consistency cost > correctness cost here.

File: src/Revisions/TaxonomyRegistrar.php [hunk 18]
```diff
@@ -0,0 +1,99 @@
...
+			[
+				'type'              => 'boolean',
+				'single'            => true,
+				'show_in_rest'      => true,
+				'sanitize_callback' => static fn( $value ): bool => (bool) $value,
+			],
+		);
+
+		register_post_meta(
+			'revision',
```
Comment (apermo) [inline src/Revisions/TaxonomyRegistrar.php]: 🟢 **Dead API surface in v0.1.0.** `register_post_meta('revision', NOTE_META, …)` registers a note meta but nothing in the PR reads or displays it — not in the overview, not in the widget, not in the column. Either wire it into the overview (show notes on hover?) or defer registration to the release that will use it. Registering now means the REST surface is frozen before there's a consumer.

File: src/Admin/OverviewPage.php (hunk 11 above)
Comment (apermo) [reply src/Admin/OverviewPage.php]: Seems related to copliot finding above

File: src/Admin/OverviewPage.php (hunk 12 above)
Comment (apermo) [reply src/Admin/OverviewPage.php:152]: Or a manual reset and disclosing the date when the cache was written?

File: src/Admin/OverviewPage.php [hunk 19]
```diff
@@ -0,0 +1,291 @@
...
+	}
+
+	/**
+	 * Handles the bulk-delete POST submission from the overview form.
+	 */
+	public static function handle_bulk_post(): void {
+		if ( ! current_user_can( self::REQUIRED_CAPABILITY ) ) {
+			wp_die( esc_html__( 'Insufficient permissions.', 'advanced-revisions' ) );
+		}
+
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Admin/OverviewPage.php:108]: Addressed in 6b1ca62 — `handle_bulk_post()` now runs every submitted parent through `current_user_can( 'edit_post', $parent_id )`. Unauthorized IDs drop out, never reach the deleter, and are reported as a separate `ar_denied` count in the completion notice.

File: src/Admin/RevisionLimitMetaBox.php [hunk 20]
```diff
@@ -0,0 +1,156 @@
...
+				$post_type,
+				LimitService::PER_POST_META_KEY,
+				[
+					'type'          => 'integer',
+					'single'        => true,
+					'show_in_rest'  => true,
+					'auth_callback' => static function ( bool $allowed, string $meta_key, int $object_id ): bool {
+						unset( $allowed, $meta_key );
+						return current_user_can( 'edit_post', $object_id );
+					},
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Admin/RevisionLimitMetaBox.php]: Addressed in 6b1ca62 — the `auth_callback` now accepts the 6-arg shape WP's `map_meta_cap()` passes (variadic `...$extras` catches trailing args for forward-compat), and honors a prior filter's strict-`false` denial instead of unconditionally overwriting the chain.

File: src/Admin/DashboardWidget.php [hunk 21]
```diff
@@ -0,0 +1,189 @@
...
+
+		// phpcs:ignore WordPress.DB.DirectDatabaseQuery -- aggregation query; cached in transient.
+		$rows = $wpdb->get_results(
+			$wpdb->prepare(
+				"SELECT p.post_title, COUNT(r.ID) AS revision_count
+					FROM %i p
+					INNER JOIN %i r
+						ON r.post_parent = p.ID AND r.post_type = 'revision'
+					WHERE p.post_type != 'revision'
+					GROUP BY p.ID
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Admin/DashboardWidget.php]: Addressed in 103d9d8 — `p.post_title` is now listed in `GROUP BY` so the query stays portable to MySQL configurations with `ONLY_FULL_GROUP_BY` that don't honor functional-dependency detection (MariaDB, managed hosts). Same fix applied to the matching query in `RevisionRepository::paginated()` (b266bb7).

File: src/Revisions/RevisionRepository.php [hunk 22]
```diff
@@ -0,0 +1,153 @@
...
+		$autosave_like = '-autosave-%';
+
+		// phpcs:ignore WordPress.DB.DirectDatabaseQuery -- aggregation count; cached per-request.
+		$count = $wpdb->get_var(
+			$wpdb->prepare(
+				"SELECT COUNT(DISTINCT r.post_parent)
+					FROM %i r
+					WHERE r.post_type = 'revision'
+						AND r.post_name NOT LIKE CONCAT(r.post_parent, %s)",
+				[
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Revisions/RevisionRepository.php]: Addressed in b266bb7 — `total_parents()` now mirrors `paginated()`'s JOIN + WHERE clauses via a shared `OVERVIEW_STATUSES` constant so the paginator denominator matches the row query. Orphan revisions and parents in trash/auto-draft no longer inflate the page count.

File: src/Admin/OverviewPage.php [hunk 23]
```diff
@@ -0,0 +1,291 @@
...
+		wp_safe_redirect(
+			self::page_url(
+				[
+					'ar_bulk'    => 'done',
+					'ar_deleted' => (string) $result['deleted'],
+					'ar_skipped' => (string) $result['skipped'],
+				],
+			),
+		);
+	}
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Admin/OverviewPage.php:165]: Addressed in 6b1ca62 — all three `wp_safe_redirect()` call sites in `handle_bulk_post()` now terminate with `exit()`.

File: src/Revisions/RevisionRepository.php [hunk 24]
```diff
@@ -0,0 +1,153 @@
...
+					COUNT(r.ID) AS revision_count,
+					MIN(r.post_date_gmt) AS oldest_gmt
+				FROM %i p
+				INNER JOIN %i r
+					ON r.post_parent = p.ID
+					AND r.post_type = 'revision'
+					AND r.post_name NOT LIKE CONCAT(p.ID, %s)
+				WHERE p.post_type != 'revision'
+					AND p.post_status IN ('publish', 'draft', 'pending', 'private', 'future')
+				GROUP BY p.ID
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Revisions/RevisionRepository.php]: Addressed in b266bb7 — every non-aggregated `p.*` column is now listed in `GROUP BY` (`p.ID, p.post_title, p.post_type, p.post_author`) so the query stays portable to MySQL configurations with `ONLY_FULL_GROUP_BY` that don't honor functional-dependency detection.

File: src/Revisions/RevisionRepository.php (hunk 9 above)
Comment (apermo) [reply src/Revisions/RevisionRepository.php:107]: Addressed in b266bb7 — `total_parents()` now mirrors `paginated()`'s JOIN + WHERE clauses via a shared `OVERVIEW_STATUSES` constant so the paginator denominator matches the row query. Orphan revisions and parents in trash/auto-draft no longer inflate the page count.

File: src/Revisions/RevisionRepository.php (hunk 10 above)
Comment (apermo) [reply src/Revisions/RevisionRepository.php:154]: Addressed in b266bb7 — extracted as `RevisionRepository::OVERVIEW_STATUSES` and applied identically in `paginated()` and `total_parents()`.

File: src/Admin/OverviewPage.php (hunk 11 above)
Comment (apermo) [reply src/Admin/OverviewPage.php]: Addressed in 6b1ca62 — default capability raised from `edit_others_posts` to `delete_others_posts` (least-privilege for a destructive cross-author op) and exposed via a filterable `OverviewPage::required_capability()` accessor backed by the `advanced_revisions_bulk_delete_capability` filter. Per-parent authorization (`edit_post` + `$post_id`) runs in addition inside `handle_bulk_post()`.

File: src/Admin/PostListColumn.php [hunk 25]
```diff
@@ -0,0 +1,279 @@
...
+		if ( $latest_revision !== null ) {
+			return add_query_arg(
+				[ 'revision' => $latest_revision ],
+				admin_url( 'revision.php' ),
+			);
+		}
+
+		$edit = get_edit_post_link( $post_id, 'raw' );
+		return \is_string( $edit ) && $edit !== '' ? $edit : admin_url();
+	}
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Admin/PostListColumn.php:151]: Addressed in dbf5228 — the existing batch-count query now also selects `MAX(ID)` per parent, populating a parallel `$latest_ids` static map in the same round-trip. `compare_url()` reads the cache for any post on the current screen; the `wp_get_post_revisions()` fallback remains for off-screen callers (CLI, bulk-action previews). Net effect: 1 query per list-table render instead of 2N+2.

File: src/Admin/DashboardWidget.php [hunk 26]
```diff
@@ -0,0 +1,189 @@
...
+		if ( $stats['total'] === 0 ) {
+			echo '<p>' . esc_html__( 'No stored revisions.', 'advanced-revisions' ) . '</p>';
+			return;
+		}
+
+		\printf(
+			'<p><strong>%1$s</strong> %2$s</p>',
+			esc_html( number_format_i18n( $stats['total'] ) ),
+			esc_html__( 'revisions stored site-wide.', 'advanced-revisions' ),
+		);
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Admin/DashboardWidget.php]: Addressed in d476c34 — replaced with a whole-sentence `_n()` call wrapped by `wp_kses( …, [ 'strong' => [] ] )`. Translators get the full sentence with `<strong>%s</strong>` as a single translatable unit; plural forms render correctly for any count.

File: src/Admin/DashboardWidget.php [hunk 27]
```diff
@@ -0,0 +1,189 @@
...
+
+		if ( $stats['est_bytes'] > 0 ) {
+			\printf(
+				'<p>%1$s <strong>%2$s</strong></p>',
+				esc_html__( 'Estimated database footprint:', 'advanced-revisions' ),
+				esc_html( size_format( $stats['est_bytes'] ) ),
+			);
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Admin/DashboardWidget.php]: Addressed in d476c34 — merged into a single translatable string with `%s` for the formatted size, passed through `wp_kses()` for the `<strong>` wrapping.

File: src/Admin/DashboardWidget.php [hunk 28]
```diff
@@ -0,0 +1,189 @@
...
+					FROM %i p
+					INNER JOIN %i r
+						ON r.post_parent = p.ID AND r.post_type = 'revision'
+					WHERE p.post_type != 'revision'
+					GROUP BY p.ID
+					ORDER BY revision_count DESC
+					LIMIT 5",
+				[ $wpdb->posts, $wpdb->posts ],
+			),
+		);
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Admin/DashboardWidget.php:223]: Addressed in 103d9d8 — all three aggregate queries in `DashboardWidget::compute()` now exclude autosaves via the `post_name NOT LIKE CONCAT(post_parent/p.ID, '-autosave-%')` pattern used elsewhere. Widget totals now match the overview page and the list-table column on sites with any autosave activity.

File: src/Revisions/ProtectionService.php [hunk 29]
```diff
@@ -0,0 +1,163 @@
...
+	private static function protected_term_lookup( array $term_ids ): array {
+		$lookup = [];
+		foreach ( $term_ids as $term_id ) {
+			$flag = get_term_meta( $term_id, TaxonomyRegistrar::PROTECTED_META, true );
+			if ( (bool) $flag ) {
+				$lookup[ $term_id ] = true;
+			}
+		}
+		return $lookup;
+	}
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Revisions/ProtectionService.php:173]: Addressed in 702d995 — `protected_term_lookup()` now calls `update_termmeta_cache( $term_ids )` before the loop to prime the object cache with a single SELECT, turning the subsequent `get_term_meta()` calls into O(1) cache hits. Completes the N+1 batching started in 1dbd63d (which batched the revision→term side).

File: src/Admin/OverviewPage.php [hunk 30]
```diff
@@ -0,0 +1,291 @@
...
+		echo '<input type="hidden" name="action" value="' . esc_attr( self::MENU_SLUG ) . '" />';
+		wp_nonce_field( self::NONCE_ACTION, self::NONCE_NAME );
+
+		echo '<p><button type="submit" class="button button-primary" name="' . esc_attr( self::BULK_FIELD ) . '" value="delete">';
+		echo esc_html__( 'Delete revisions for selected posts', 'advanced-revisions' );
+		echo '</button></p>';
+
+		echo '<table class="wp-list-table widefat fixed striped">';
+		echo '<thead><tr>';
+		echo '<td class="manage-column column-cb check-column"><input type="checkbox" id="cb-select-all-1" /></td>';
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Admin/OverviewPage.php]: Addressed in a4c7801 — the select-all checkbox now carries a `<label class="screen-reader-text" for="cb-select-all-1">Select all posts</label>` matching the core list-table pattern.

File: docs/testing.md [hunk 31]
```diff
@@ -0,0 +1,143 @@
...
+| #1    | Per-type revision limit              |  ✓   |             |     | `mixed-types`     |
+| #2    | Admin overview                       |  ✓   |             |     | `heavy-site`      |
+| #3    | Bulk delete from overview            |  ✓   |             |     | `heavy-site`      |
+| #4    | Post list column                     |  ✓   |             |     | `normal-site`     |
+| #10   | Dashboard widget                     |  ✓   |             |     | `normal-site`     |
+| #11   | Per-post override                    |  ✓   |             |     | `mixed-types`     |
+| #13   | Tagging + protection                 |  ✓   |             |     | `tagged-site`     |
+| #14   | Dev fixtures CPTs                    |  ✓   |             |     | n/a               |
+| #15   | Content seeder (WP-CLI)              |  ✓   |             |     | n/a               |
+| #16   | Revision seeder (WP-CLI)             |  ✓   |             |     | n/a               |
```
[the remark this answers is not in the document]
Comment (apermo) [reply docs/testing.md]: Addressed in 9b8b2ef — every empty Integration/E2E cell now shows `—` matching the legend. Unit coverage shipped with v0.1.0, the other two layers are deferred with infrastructure in place.

File: src/Admin/OverviewPage.php [hunk 32]
```diff
@@ -0,0 +1,291 @@
...
+	 * @param array<string, mixed> $row_data One row from RevisionRepository::paginated().
+	 */
+	private static function render_row( array $row_data ): void {
+		$edit_link = (string) get_edit_post_link( $row_data['id'] );
+
+		echo '<tr>';
+		\printf(
+			'<th class="check-column"><input type="checkbox" name="ar_parent_ids[]" value="%s" /></th>',
+			esc_attr( (string) $row_data['id'] ),
+		);
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Admin/OverviewPage.php:309]: Addressed in a4c7801 — each row checkbox gets a unique `id="cb-select-{ID}"` paired with a screen-reader-only label reading "Select {post title}" (falling back to the localized "(no title)" for untitled posts).

File: src/Revisions/RevisionDeleter.php (hunk 14 above)
Comment (apermo) [reply src/Revisions/RevisionDeleter.php]: Addressed in 8cd4423 — one-line comment added flagging that the subtraction-based count avoids a second `terms_by_revision` fetch, so a future "simplification" doesn't regress performance.

File: src/Admin/RevisionLimitMetaBox.php (hunk 15 above)
Comment (apermo) [reply src/Admin/RevisionLimitMetaBox.php:40]: Addressed in 45530cd — moved `register_post_meta()` from `init` priority 10 to `wp_loaded`. `wp_loaded` fires after every plugin's init, so `revisable_post_types()` now sees CPTs registered at any init priority.

File: src/Admin/PostListColumn.php (hunk 16 above)
Comment (apermo) [reply src/Admin/PostListColumn.php]: Addressed in 8cd4423 — `current_screen_post_ids()` is now typed `?WP_Query` with an `instanceof WP_Query` narrow at the top; `WP_Query` imported at the top of the file.

File: src/Admin/OverviewPage.php (hunk 17 above)
Comment (apermo) [reply src/Admin/OverviewPage.php]: Addressed in 8cd4423 — `$_GET['ar_bulk']` now runs through `wp_unslash()` before `sanitize_key()`, matching the unslash+sanitize pattern used elsewhere in the file.

File: src/Revisions/TaxonomyRegistrar.php (hunk 18 above)
Comment (apermo) [reply src/Revisions/TaxonomyRegistrar.php]: Addressed in 677f661 — removed the `NOTE_META` registration and the constant. No consumer in v0.1.0 read or displayed it; locking the REST surface before there's a caller is premature. The release that wires up per-revision notes can reintroduce it with semantics chosen for that context.
